dist: xenial

addons:
    apt:
        packages:
            - tcl-dev
            - openssl
            - bats
            - libssl-dev 
            - zlib1g-dev
            - procps
            - netcat
            - bats
            - tar
            - telnet
language: C

services:
    - docker

compiler:
    - gcc

env:
    global:
        - MAKEFLAGS="-j 2"

before_install:
    - git clone https://github.com/eggheads/eggdrop-tests.git
    - docker build -t eggdrop:gitcmp https://github.com/eggheads/eggdrop-tests.git#master:Dockerfiles/dockerfile_git_compiled

jobs:
    include:
          script: 
            - bats eggdrop-tests/eggdrop_compile_configure.bats
            - bats eggdrop-tests/eggdrop_compile_make.bats
            - bats eggdrop-tests/eggdrop_compile_testrun.bats
            - docker run --rm -v $TRAVIS_BUILD_DIR/eggdrop-tests/:/tmp/build/tests/ eggdrop:gitcmp bash -c "bats /tmp/build/tests/eggdrop_tcl_matchattr.bats"
            - docker run --rm -v $TRAVIS_BUILD_DIR/eggdrop-tests/:/tmp/build/tests/ eggdrop:gitcmp bash -c "bats /tmp/build/tests/eggdrop_tcl_iscmds.bats"
            - docker run --rm -v $TRAVIS_BUILD_DIR/eggdrop-tests/:/tmp/build/tests/ eggdrop:gitcmp bash -c "bats /tmp/build/tests/eggdrop_tcl_passwdok.bats"
            - docker run --rm -v $TRAVIS_BUILD_DIR/eggdrop-tests/:/tmp/build/tests/ eggdrop:gitcmp bash -c "bats /tmp/build/tests/eggdrop_partyline_bans.bats"
            - docker run --rm -v $TRAVIS_BUILD_DIR/eggdrop-tests/:/tmp/build/tests/ eggdrop:gitcmp bash -c "bats /tmp/build/tests/eggdrop_partyline_flags.bats"
            - docker run --rm -v $TRAVIS_BUILD_DIR/eggdrop-tests/:/tmp/build/tests/ eggdrop:gitcmp bash -c "bats /tmp/build/tests/eggdrop_botnet_linking.bats"
            - docker run --rm -v $TRAVIS_BUILD_DIR/eggdrop-tests/:/tmp/build/tests/ eggdrop:gitcmp bash -c "bats /tmp/build/tests/eggdrop_chanset_inputvalidation.bats"

###################################################################################
#    - echo travis:$foop | sudo chpasswd
#    - sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
#    - sudo service ssh restart
#    - sudo apt-get install sshpass
#    - sshpass -p $foop ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no travis@$bouncehostip
