dist: xenial

addons:
    apt:
        packages:
            - tcl-dev
            - openssl
            - bats
            - libssl-dev 
            - zlib1g-dev
            - procps
            - netcat
            - bats
            - tar
            - telnet
language: C

services:
    - docker

compiler:
    - gcc
    - clang

before_install:
    - git clone https://github.com/eggheads/eggdrop-tests.git
#    - docker build https://github.com/eggheads/eggdrop-docker.git#master:develop

script: 
#    - ./configure && make config && make && make install && make test
    - pwd
    - ls $HOME
    - bats eggdrop-tests/eggdrop_compile_configure.bats
    - bats eggdrop-tests/eggdrop_compile_make.bats
