name: CI

on:
  push:
  repository_dispatch:
  schedule:
    - cron: '3 4 * * 1'

env:
  TRAVIS_BUILD_DIR: /home/runner/work/eggdrop/eggdrop
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt-get install bats tcl tcl-dev openssl libssl-dev gcc make
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out tests
        uses: actions/checkout@v2
        with:
          repository: eggheads/eggdrop-tests
          path: tests
      - name: Run config test
        run: bats tests/eggdrop_compile_configure.bats
#      - name: Test
#        run: bats -r 
  test:
    if: github.event.action == 'run_tests'
    name: Run BATS tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I just ran all your tests!"
