name: CI

on:
  push:
  repository_dispatch:
  schedule:
    - cron: '3 4 * * 1'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt-get install bats
      - name: Check out code
        uses: actions/checkout@v1
      - name: Check out tests
        uses: eggheads/eggdrop-tests
        with:
          path: /tmp/build/tests
#      - name: Test
#        run: bats -r 
  test:
    if: github.event.action == 'run_tests'
    name: Run BATS tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I just ran all your tests!"
